GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "probando otra vez si sale userID",
    "important": false,
    "userId": "666856ffbc449945449331f2"
}