GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGx5IiwiaWQiOiI2N2E4YTNlZDI3ZTZjYTYwZTBlZTkwNTgiLCJpYXQiOjE3MzkxMDU4MzgsImV4cCI6MTczOTEwOTQzOH0.r9wBM3HfWNZE5P1W93oypPZyRtLC2WhDkRMJV5AEh5k

{
    "content": "probando creación de notas con jwt",
    "important": true
}